---
- hosts: slave
  become: true
  vars:
    agent_name: slave
    server_name: master
  tasks:
    - name: Install puppet-common
      apt:
       state: present
       name: puppet-common
    - name: Install package from .deb file
      apt:
        deb: https://apt.puppetlabs.com/puppet6-release-focal.deb
      ignore_errors: true
    - name: Install puppet agent
      apt:
        state: present
        name: puppet-agent
      ignore_errors: true
    - name: Config path to access puppet commands
      shell: export PATH=/opt/puppetlabs/bin:$PATH
    - name: Changing directory to path of puppet
      shell: cd /opt/puppetlabs/bin 
    - name: Configure server settings
      shell: puppet config set server 172.31.24.17 --section main
      ignore_errors: true
    - name: Connect agent to primary
      shell: puppet ssl bootstrap
      ignore_errors: true
    - name: Sign Certificate
      shell: sudo puppetserver ca sign --certname 172.31.29.118
      delegate_to: 172.31.24.17
      ignore_errors: true
    - name: Connect agent to primary
      shell: puppet ssl bootstrap
      ignore_errors: true
